# Generated by Django 4.2.4 on 2023-09-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'verbose_name': 'Инструкция', 'verbose_name_plural': 'Инструкции'},
        ),
    ]
