# Generated by Django 4.2.4 on 2023-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_alter_instruction_author_alter_instruction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='instruction_files/', verbose_name='Файл инструкции'),
        ),
    ]
