# Generated by Django 4.2.4 on 2023-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to="instruction_files/<class 'instructions.models.Category'>/", verbose_name='Файл инструкции'),
        ),
    ]
