# Generated by Django 4.2.4 on 2023-09-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0009_remove_instruction_file_path_instruction_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(null=True, upload_to='instruction_files/None/'),
        ),
    ]
