# Generated by Django 4.2.4 on 2023-09-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0010_alter_instruction_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(null=True, upload_to='instruction_files/<django.db.models.query_utils.DeferredAttribute object at 0x10e3ed810>/'),
        ),
    ]
