# Generated by Django 4.2.4 on 2023-09-11 13:16

from django.db import migrations, models
import instructions.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0011_alter_instruction_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='file',
            field=models.FileField(null=True, upload_to=instructions.models.instruction_file_upload_path),
        ),
    ]
