# Generated by Django 4.2.4 on 2023-09-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=30, null=True)),
                ('sap', models.CharField(max_length=10, null=True)),
                ('legal_entity', models.CharField(max_length=100, null=True)),
                ('addres_object', models.TextField(max_length=200, null=True)),
                ('nomer_pos', models.IntegerField(max_length=3, null=True)),
                ('model_fr', models.CharField(max_length=20, null=True, verbose_name='Модель ФР')),
                ('sn_fr', models.BigIntegerField(max_length=20, null=True, verbose_name='Серийный номер ФР')),
                ('sn_fn', models.BigIntegerField(max_length=40, null=True, verbose_name='Серийный номер ФН')),
                ('date_fp', models.DateField(null=True)),
                ('replacement_date', models.DateField(null=True)),
                ('regions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.regions', verbose_name='Регион нахождения объекта')),
            ],
            options={
                'verbose_name': 'График замен ФН',
            },
        ),
    ]
