# Generated by Django 4.2.4 on 2023-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FnReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_object', models.CharField(max_length=30)),
                ('sap', models.CharField(max_length=10)),
                ('legal_entity', models.CharField(max_length=100)),
                ('nomer_pos', models.IntegerField(max_length=3)),
                ('model_fr', models.CharField(max_length=20)),
                ('sn_fr', models.IntegerField(max_length=20)),
                ('sn_fn', models.IntegerField(max_length=40)),
                ('date_fp', models.DateField()),
                ('replacement_date', models.DateField()),
            ],
            options={
                'verbose_name': 'График замен ФН',
            },
        ),
    ]
