# Generated by Django 4.2.4 on 2023-09-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnreplacement',
            name='legal_entity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='model_fr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='name_object',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='nomer_pos',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='sap',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='sn_fn',
            field=models.BigIntegerField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='sn_fr',
            field=models.BigIntegerField(max_length=20, null=True),
        ),
    ]
