# Generated by Django 4.2.4 on 2023-09-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0002_alter_fnreplacement_legal_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnreplacement',
            name='addres_object',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
