# Generated by Django 4.2.4 on 2023-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fn', '0003_fnreplacement_addres_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnreplacement',
            name='date_fp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fnreplacement',
            name='replacement_date',
            field=models.DateField(null=True),
        ),
    ]
