# Generated by Django 4.2.4 on 2023-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_alter_objects_regions'),
        ('fn', '0004_alter_fnreplacement_date_fp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnreplacement',
            name='regions',
            field=models.ManyToManyField(max_length=70, null=True, to='parameters.regions'),
        ),
    ]
