# Generated by Django 4.2.4 on 2023-09-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_alter_objects_regions'),
        ('fn', '0005_fnreplacement_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fnreplacement',
            name='regions',
        ),
        migrations.AddField(
            model_name='fnreplacement',
            name='regions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parameters.regions', verbose_name='Регион нахождения объекта'),
        ),
    ]
