# Generated by Django 4.2.4 on 2023-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_alter_objects_regions'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='regions',
            field=models.ManyToManyField(blank=True, to='parameters.regions'),
        ),
    ]
