# Generated by Django 4.2.4 on 2023-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=30, verbose_name='Автор')),
                ('name', models.CharField(max_length=40, verbose_name='Название поста')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание поста')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на инструкцию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
