# Generated by Django 4.2.4 on 2023-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=0, max_length=40, verbose_name='Название поста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на инструкцию'),
        ),
    ]
