# Generated by Django 4.2.4 on 2023-09-14 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(default=django.utils.timezone.now, max_length=30, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
