# Generated by Django 4.2.4 on 2023-09-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион работы',
                'verbose_name_plural': 'Регионы работы',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Номер объекта')),
                ('sap', models.CharField(max_length=4, null=True, verbose_name='SAP')),
                ('address', models.CharField(max_length=40, null=True, verbose_name='Адрес объекта')),
                ('regions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.regions', verbose_name='Регион нахождения объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
